<?php
/**
 * /admin/invoices.php — platform admin invoice manager.
 *
 * Table of every invoice: number, workspace, plan, amount, status,
 * sent-to email + when, paid-at. Per-row actions:
 *   - View (opens the customer-facing viewer in a new tab)
 *   - Mark paid  (updates status = paid + optional note)
 *   - Void       (status = void, no more chasing)
 *   - Resend email
 *
 * Also lets platform admin manually create an invoice for any workspace
 * (for offline sales / carry-overs from before the cron existed).
 */
require_once __DIR__ . '/../inc/layout.php';
require_once __DIR__ . '/../inc/invoicing.php';

$current_user = require_login();
if (!is_platform_admin()) {
    http_response_code(403);
    exit('Platform admin access only.');
}

$db = aiserve_db();

$msg = '';
$err = '';

// -------------------- Actions --------------------
if (is_post()) {
    csrf_check();
    $action = (string)($_POST['action'] ?? '');
    $id     = (int)($_POST['invoice_id'] ?? 0);

    if ($action === 'mark_paid' && $id > 0) {
        $note = mb_substr(trim((string)($_POST['paid_note'] ?? '')), 0, 255);
        $db->prepare('UPDATE invoices SET status = "paid", paid_at = NOW(), paid_note = ? WHERE id = ?')
           ->execute([$note ?: null, $id]);
        log_activity(0, (int)$current_user['id'], 'invoice_marked_paid', 'invoice', $id, $note);
        $msg = 'Invoice marked paid.';
    } elseif ($action === 'void' && $id > 0) {
        $db->prepare('UPDATE invoices SET status = "void" WHERE id = ?')->execute([$id]);
        log_activity(0, (int)$current_user['id'], 'invoice_voided', 'invoice', $id);
        $msg = 'Invoice voided.';
    } elseif ($action === 'resend' && $id > 0) {
        $ok = invoicing_send_email($id);
        $msg = $ok ? 'Invoice resent by email.' : 'Could not resend — check the mail log.';
        if (!$ok) $err = $msg;
        else      $err = '';
    }
}

// -------------------- Query --------------------
$fStatus = (string)($_GET['status'] ?? 'all');
$where   = [];
$params  = [];
if (in_array($fStatus, ['draft','sent','paid','void'], true)) {
    $where[]  = 'i.status = ?';
    $params[] = $fStatus;
}
$sql = 'SELECT i.*, c.name AS company_name, c.slug AS company_slug
        FROM invoices i
        INNER JOIN companies c ON c.id = i.company_id'
     . ($where ? ' WHERE ' . implode(' AND ', $where) : '')
     . ' ORDER BY i.id DESC LIMIT 200';
$s = $db->prepare($sql);
$s->execute($params);
$rows = $s->fetchAll();

// KPIs (across all invoices, not just filtered)
$agg = $db->query(
    "SELECT status, COUNT(*) AS n, SUM(total) AS gross
     FROM invoices GROUP BY status"
)->fetchAll();
$k = ['draft'=>0,'sent'=>0,'paid'=>0,'void'=>0];
$gross = ['sent'=>0.0, 'paid'=>0.0];
foreach ($agg as $r) {
    $k[$r['status']] = (int)$r['n'];
    if (isset($gross[$r['status']])) $gross[$r['status']] = (float)$r['gross'];
}

layout_start($current_user, 'Invoices', 'invoices');
?>
<style>
.iv-kpi-row { display:grid; gap:10px; grid-template-columns: repeat(4,1fr); margin-bottom:14px; }
@media (max-width: 900px) { .iv-kpi-row { grid-template-columns: repeat(2,1fr); } }
.iv-kpi { background:#fff; border:1px solid #e3e8ee; border-radius:10px; padding:12px 14px; }
.iv-kpi .lbl { color:#64748b; font-size:11px; text-transform:uppercase; letter-spacing:.04em; }
.iv-kpi .val { font-size:22px; font-weight:700; }
.iv-status  { display:inline-block; padding:2px 8px; border-radius:999px; font-size:11px; font-weight:600; }
.iv-draft   { background:#f1f5f9; color:#64748b; }
.iv-sent    { background:#dbeafe; color:#1e3a8a; }
.iv-paid    { background:#dcfce7; color:#14532d; }
.iv-void    { background:#fee2e2; color:#7f1d1d; }
</style>

<div class="card">
    <h2>💳 Invoices</h2>
    <p class="muted small">
        Every invoice generated by the upgrade cron, plus any manual ones. Mark paid when
        payment arrives. Cron reads activity_logs of type
        <code>broadcast_plan_selfserve_change</code> and creates one invoice per upgrade
        (idempotent — UNIQUE on source_activity_id).
    </p>

    <?php if ($msg): ?><div class="alert alert-success"><?= e($msg) ?></div><?php endif; ?>
    <?php if ($err): ?><div class="alert alert-error"><?= e($err) ?></div><?php endif; ?>

    <div class="iv-kpi-row">
        <div class="iv-kpi"><div class="lbl">Draft</div><div class="val" style="color:#64748b;"><?= (int)$k['draft'] ?></div></div>
        <div class="iv-kpi">
            <div class="lbl">Sent · awaiting payment</div>
            <div class="val" style="color:#1e3a8a;"><?= (int)$k['sent'] ?></div>
            <div class="muted small">RM <?= number_format($gross['sent'], 2) ?> outstanding</div>
        </div>
        <div class="iv-kpi">
            <div class="lbl">Paid · this year</div>
            <div class="val" style="color:#16A34A;"><?= (int)$k['paid'] ?></div>
            <div class="muted small">RM <?= number_format($gross['paid'], 2) ?> collected</div>
        </div>
        <div class="iv-kpi">
            <div class="lbl">Void</div>
            <div class="val" style="color:#7f1d1d;"><?= (int)$k['void'] ?></div>
        </div>
    </div>

    <form method="get" style="display:flex; gap:8px; align-items:center; margin-bottom:12px;">
        <select name="status" onchange="this.form.submit()">
            <option value="all"   <?= $fStatus === 'all'   ? 'selected' : '' ?>>All status</option>
            <option value="draft" <?= $fStatus === 'draft' ? 'selected' : '' ?>>Draft</option>
            <option value="sent"  <?= $fStatus === 'sent'  ? 'selected' : '' ?>>Sent (chase)</option>
            <option value="paid"  <?= $fStatus === 'paid'  ? 'selected' : '' ?>>Paid</option>
            <option value="void"  <?= $fStatus === 'void'  ? 'selected' : '' ?>>Void</option>
        </select>
        <span class="muted small"><?= count($rows) ?> invoice(s) shown</span>
    </form>

    <table class="data-table">
        <thead>
            <tr>
                <th>Invoice #</th>
                <th>Workspace</th>
                <th>Item</th>
                <th style="text-align:right;">Total</th>
                <th>Status</th>
                <th>Emailed</th>
                <th>Paid</th>
                <th style="text-align:right;">Actions</th>
            </tr>
        </thead>
        <tbody>
            <?php if (!$rows): ?>
                <tr><td colspan="8" class="muted" style="text-align:center; padding:24px;">
                    No invoices yet — they'll appear here as workspaces upgrade (or wait for the cron to run).
                </td></tr>
            <?php endif; ?>

            <?php foreach ($rows as $r):
                $viewUrl = '/invoice.php?id=' . (int)$r['id'] . '&token=' . urlencode((string)$r['view_token']);
            ?>
                <tr>
                    <td>
                        <a href="<?= e($viewUrl) ?>" target="_blank" title="Open invoice">
                            <?= e((string)$r['invoice_number']) ?>
                        </a>
                        <div class="muted small"><?= e(fmt_dt((string)$r['created_at'])) ?></div>
                    </td>
                    <td>
                        <?= e((string)$r['company_name']) ?>
                        <div class="muted small"><code><?= e((string)$r['company_slug']) ?></code></div>
                    </td>
                    <td>
                        <?= e(ucfirst((string)$r['plan'])) ?>
                        <span class="muted small">/ <?= e((string)$r['billing_cycle']) ?></span>
                    </td>
                    <td style="text-align:right; font-variant-numeric: tabular-nums;">
                        <?= e((string)$r['currency']) ?> <?= number_format((float)$r['total'], 2) ?>
                    </td>
                    <td><span class="iv-status iv-<?= e((string)$r['status']) ?>"><?= e((string)$r['status']) ?></span></td>
                    <td class="muted small">
                        <?= $r['email_sent_at']
                            ? e(fmt_dt((string)$r['email_sent_at'])) . '<br><small>' . e((string)$r['email_sent_to']) . '</small>'
                            : '—' ?>
                    </td>
                    <td class="muted small">
                        <?= $r['paid_at'] ? e(fmt_dt((string)$r['paid_at'])) : '—' ?>
                        <?php if ($r['paid_note']): ?><br><small><?= e((string)$r['paid_note']) ?></small><?php endif; ?>
                    </td>
                    <td style="text-align:right; white-space:nowrap;">
                        <?php if ($r['status'] !== 'paid' && $r['status'] !== 'void'): ?>
                            <form method="post" style="display:inline;"
                                  onsubmit="var n = prompt('Payment reference / note (optional):'); if (n===null) return false; this.paid_note.value=n; return true;">
                                <?= csrf_field() ?>
                                <input type="hidden" name="action"     value="mark_paid">
                                <input type="hidden" name="invoice_id" value="<?= (int)$r['id'] ?>">
                                <input type="hidden" name="paid_note"  value="">
                                <button class="btn btn-sm btn-primary" type="submit">✓ Paid</button>
                            </form>
                            <form method="post" style="display:inline;"
                                  onsubmit="return confirm('Resend invoice email?');">
                                <?= csrf_field() ?>
                                <input type="hidden" name="action"     value="resend">
                                <input type="hidden" name="invoice_id" value="<?= (int)$r['id'] ?>">
                                <button class="btn btn-sm" type="submit">↻ Resend</button>
                            </form>
                            <form method="post" style="display:inline;"
                                  onsubmit="return confirm('Void this invoice?');">
                                <?= csrf_field() ?>
                                <input type="hidden" name="action"     value="void">
                                <input type="hidden" name="invoice_id" value="<?= (int)$r['id'] ?>">
                                <button class="btn btn-sm btn-danger" type="submit">Void</button>
                            </form>
                        <?php endif; ?>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>

<?php layout_end(); ?>
